### PR TITLE
Added support for RTX 30xx cards.

### PR DESCRIPTION
**Pull request by MoFtZ**
Added support for RTX 30xx cards, as spotted in https://github.com/m4rs-mt/ILGPU/pull/25#issuecomment-719117666.

### CODE REVIEW

**Review by m4rs-mt — APPROVED** [review]
Awesome patch 🚀

**Comment by MoFtZ** [comment]
I'm thinking I might raise another PR, that would add a ContextFlag to ignore the driver check. That way, it could be used on newer cards until ILGPU is updated.

What do you think?

**Comment by m4rs-mt** [comment]
@MoFtZ Makes sense to me. In these cases you could try ILGPU on newer hardware without waiting for us to update the code and do further compatibility checks.

**Comment by MoFtZ** [comment]
Actually, made a different/easier change.

If the graphics card is on an PTX architecture that ILGPU does not know about, the user must be using a newer graphics cards. This newer card will require new drivers, so it should work just fine.

The only issue would be if the newer drivers dropped support for the PTX instruction sets that we support, but the risk is very small.

**Comment by m4rs-mt** [comment]
@MoFtZ I totally agree. The risk should be very small. Usually, an instruction can become obsolete when upgrading the PTX version, which should not happen when upgrading the drivers.

**Pull request merged**
