### PR TITLE
Hot fix for ILGPU not detecting AMD Cards

### PR DESCRIPTION
**Pull request by 12345swordy**
As promised, I create a hot-fix pull request for this. I can't for the life of me get the t4 templates to work for ILGPU.Algorithms projects, so I need this patch to merge asap.

### CODE REVIEW

**Comment by m4rs-mt** [comment]
@12345swordy Thank you for your PR. However, I would prefer a more generic solution than allocating an array of `short.MaxValue` length containing `IntPtr` structures in the scope of every call. As described in #49, we should focus on redesigning the `CLAccelerator` constructor and basically remove the `GetNumDevices` function completely from the public `CLAPI`. Moreover, there are additional issues regarding this functionality that have to be solved anyway (see #49).

**Comment by m4rs-mt** [comment]
> I can't for the life of me get the t4 templates to work for ILGPU.Algorithms projects, so I need this patch to merge asap.

I'm not sure what you mean. Are you talking about the T4 templates in both (the `ILGPU` and the `ILGPU.Algorithms`) packages in general? Also, I'm not sure how quickly merging this PR would solve this problem, as the next public release cycle will take place in several weeks. However, you can still create the project using VS2019 and create your own Nuget package instance using the build script provided.

**Comment by m4rs-mt** [comment]
@12345swordy: What about this potential fix 1f3ebbd824acfa079bf4d3259fcf39b567f0438f?

**Comment by 12345swordy** [comment]
That will work.

**Comment by 12345swordy** [comment]
I was talking about the "algorithms" package, yes. I can't for the life of me get the t4 to generate code for me that doesn't consist of ambiguous error messages.

**Comment by m4rs-mt** [comment]
@12345swordy hmm this could be a problem in the T4 templates in the `ILGPU.Algorithms` repository. Can you create an issue in the `ILGPU.Algorithms` repository that contains all the steps to reproduce this problem?

**Comment by m4rs-mt** [comment]
I am going to create a bug-fix release (`v0.7.0.1`) at the end of the week. This also includes the latest workarounds for AMD and other vendors.

**Pull request closed without merging**
