### PR TITLE
Add ephemeral dynamic runners workflow and config

### PR DESCRIPTION
**Pull request by pavlovic-ivan**
**Intention**

The intention of this PR is to provide the project the ability to deploy dynamic runners that will run CUDA jobs, by adding new runners workflow. In order to have the complete feature, Github repo needs to be configured. More about that bellow in the Guide.

**Guide**

This guide explains how to configure Github repo. First, the prerequisits. You need a protected environment. If none exist:

1. Go to `Settings` > `Environments` > `New environment`
2. Give the Environment a name `cuda-test-infra`
3. Select a branch for which this Environment will be available by selecting the option "Selected branches" in the drop down menu of `Deployment branches`.
4. Select "+ Add deployment branch rule"
5. In the popup window enter the name of the main branch (eg, main, master, whichever is the main for your repo)

Now, make sure you have a Personal Access Token (PAT) set. If not:

1. Open Your Profile > `Settings` > `Developer Settings` > `Personal access tokens`
2. Select `Generate new token`
3. Give the token a name
4. Set expiration to "No expiration"
5. Select scopes for the token: `repo: Full control of private repositories`
6. Select `Generate token`
7. Copy the token and save it, it is visible to you only once

After the Environment [exists/is created], add new Environment secrets (provided safely offline), but:

- Select "+ Add Secret" within selected Environment (Environment named `cuda-test-infra`)

**Working example**

A working example can be seen [here](https://github.com/pavlovic-ivan/ILGPU-fork2/actions/runs/1848580697). You will see that CUDA tests are green. Workflow failed on `publish-preview` job, as i don't have perms and secrets needed to make it successful.

When this workflow was created, it created an event that triggered a workflow that deploys the runners. Workflow available [here](https://github.com/pavlovic-ivan/ILGPU-fork2/actions/runs/1848580754). Once the main CI workflow is done, another event triggers a workflow that destroys the created runners (as seen [here](https://github.com/pavlovic-ivan/ILGPU-fork2/actions/runs/1848719253)).

**Further steps before accepting PR**

- [ ] Communicate securely with upstream maintainer. Provide secrets needed to deploy runners to GR GCP project

Co-authored-by: Jonathan Giannuzzi jonathan@giannuzzi.me

### CODE REVIEW

**Comment by m4rs-mt** [comment]
@pavlovic-ivan Thank you so much for your hard work on this topic and your PR 🚀🏅 I will be in touch with @jgiannuzzi to integrate everything "behind the scenes".

**Comment by pavlovic-ivan** [comment]
@m4rs-mt my pleasure :)

**Comment by pavlovic-ivan** [comment]
Hi @m4rs-mt @jgiannuzzi. Latest changes and PRs to the repos https://github.com/pavlovic-ivan/ephemeral-github-runner-gcp and https://github.com/pavlovic-ivan/ephemeral-github-runner-image-gcp have been merged. These bring more security and usage of Github App. Feel free to rebase your forks.

**Comment by m4rs-mt** [comment]
Thank you for working on this issue. Since PR #770 supersedes this PR, we are closing this PR for now.

**Pull request closed without merging**
