### PR TITLE
Static analysis

### PR DESCRIPTION
**Pull request by MoFtZ**
hi @m4rs-mt, I have started working on updating the static analysis as per #41.

I had some questions for you regarding a few of the issues that came up.

- [x] Disposable-related warnings

  CA1001: Types that own disposable fields should be disposable
  CA2000: Dispose objects before losing scope
  CA2213: Disposable fields should be disposed

  It looks like a number of these have been ignored/suppressed in the past. Should I continue to suppress these warnings?

- [x] CA1060: Move pinvokes to native methods class

  This was part of your recent changes to support OpenCL. I was not planning to make any changes in case they caused conflicts with your pending commits.

- [x] [CA2225: Operator overloads have named alternates](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2225?view=vs-2019)

  It looks like it is recommended that operators have a matching named method. So:
  ```
  public static implicit operator ArrayView<T, Index>(ArrayView<T> view)
  {
      return new ArrayView<T, Index>(view, view.Length);
  }
  ```
  would have a new method:
  ```
  public ArrayView<T, Index> ToArrayView();
  ```
  What are your thoughts on this recommendation? Implement or Suppress?

### CODE REVIEW

**Comment by MoFtZ** [comment]
There are also a number of code styling issues, which are subjective. Do you prefer to use the new style, or keep the existing style?

- [ ] IDE0019: Use pattern matching
    ```
    switch (value)
    {
        case 0:
            value = 7;
            break;
        case 1:
            value = 42;
            break;
        case 2:
            value = 1337;
            break;
        default:
            value = -1;
            break;
    }
    ```
   can be changed to:
    ```
    value = value switch
    {
        0 => 7,
        1 => 42,
        2 => 1337,
        _ => -1,
    };
    ```
- [ ] IDE0034: 'default' expression can be simplified

    ```
   Current = default(LocalVariable);
    ```
   can be changed to:
    ```
   Current = default;
    ```
- [ ] IDE0063: 'using' statement can be simplified
 
    ```
    using (var buffer = Accelerator.Allocate<int>(1))
    {
        Execute<Index>(specializedMethod, buffer.Length, buffer.View);

        var size = Marshal.SizeOf(type);
        var expected = new int[] { size };
        Verify(buffer, expected);
    }
    ```
   can be changed to:
    ```
    using var buffer = Accelerator.Allocate<int>(1);
    Execute<Index>(specializedMethod, buffer.Length, buffer.View);

    var size = Marshal.SizeOf(type);
    var expected = new int[] { size };
    Verify(buffer, expected);
    ```

**Comment by m4rs-mt** [comment]
@MoFtZ First of all: thank you very much for diving into this topic :)

1. Regarding the `IDisposable` question
Some warnings have been suppressed in the past because static analysis cannot check whether the `DisposeBase.Dispose(ref object)` method actually disposes of the object and sets the referenced field to `null`. Should we simply change this, since it is no longer necessary to set fields to zero, since multiple calls to the `Dispose` method are "intercepted" by the `DisposeBase` anyway. What do you think?
2. I already expected something like this to happen. I ignore some of these warnings in the past to simplify the integration of the `CudaAPI` method calls due to native imports from different Cuda libraries. I am going to update the `OpenCL` part of the project after you have updated the static analysis part.
3. I guess it makes sense to implement them in most of the cases. However, since we usually target the "core" .NET world it might not be required in all cases. What do you think?

**Comment by m4rs-mt** [comment]
Regarding the guidelines on the "new coding style": I guess we should follow them. For example, the new `using` statements and simplified `default` keywords make it much easier to understand and structure the code. What do you think?

I can also apply the new coding styles to the source code after you've done the updated analysis. Of course you can also apply the changes to all source files, but I'd like to ask you to omit the `IR` and `Backend` packages as I'm working on them anyway.

**Comment by MoFtZ** [comment]
@m4rs-mt, it sounds like the implementation of `IDisposable` and `DisposeBase` should be reviewed. For now, I'm going to suppress the warnings - it can be handled in separate enhancement.

For `CA2225: Operator overloads have named alternates`, I'm going to suppress this too. Again, it can be handled in a separate enhancement, and as long as there are no issues with the current API, there is no urgency to implement the named alternatives.

I have also updated the source code to remove all warnings/messages except for in `IR` and `Backend`.

**Pull request merged**
