### PR TITLE
Use publish-test-result GH action

### PR DESCRIPTION
**Pull request by EnricoMi**
- Uses the [publish-test-result GH action](https://github.com/EnricoMi/publish-unit-test-result-action) instead of the GitHubAction logger
- Combines all test jobs in a single summary
- Uploads test result files for inspection
- Posts test summary to pull requests
- Reports test changes (accidentally skipped or removed tests)

There are 54 tests that are always skipped (across all .Net versions and Frameworks)

### CODE REVIEW

**Comment by m4rs-mt** [comment]
Adding @jgiannuzzi

**Comment by EnricoMi** [comment]
@MoFtZ please approve this workflow so we can see it works, then I will have to remove something from the CI workflow before this is ready to be merged.

**Comment by MoFtZ** [comment]
hi @EnricoMi. thanks for taking an interest in this project, and submitting a PR.

Looking at the changes you have made, I can see that the pipeline will now upload the contents of `github.event_path` as a build artifact. Looking at the instructions for the [publish-unit-test-result](https://github.com/EnricoMi/publish-unit-test-result-action) action, it does not appear to mention this step. Are you able to explain this file? Are there any secrets that might be accidentally revealed?

The 54 tests that are skipped are likely the CPU tests that have [a small number of threads](https://github.com/m4rs-mt/ILGPU/blob/deceb21b33704ec6f6474a895d9bff96a03262b3/Src/ILGPU.Tests/WarpOperations.cs#L299). Looking at the output, am I correct in assuming that the test results are not interactive? That is, if I wanted to find out which tests are always being skipped, can I click on a link?
image

Since this PR replaces the existing GitHubActionsTestLogger, should the PR be updated to remove the GitHubActionsTestLogger nuget packages from the various projects? Also, what are the pros/cons of this new GH action over GitHubActionsTestLogger?

**Comment by EnricoMi** [comment]
Thanks for looking into this!

The event file is required to fully work for pull requests from fork repositories and dependabot branches as well. The details can be found further down in the README.md: https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches

I have inspected a couple of event files for various event types in multiple situations, and none had sensitive information.

The action creates a list of all tests, and of all skipped tests as an annotation (but only for commits on master). Those lists are used to detect changes in the number of tests (in pull requests and between consecutive commits). If new skipped tests appear, they are listed in the pull request comment itself.

You are right, the `GitHubActionsTestLogger` can be removed, which I will do this soon.

In general, the pros/cons of this GH action are:
- [a comment](https://github.com/EnricoMi/publish-unit-test-result-action#pull-request-comment) in related pull requests is created, it highlights removed or newly skipped tests, links directly to the annotations if some exists, changes in test result files (fewer result files created which indicates reduced test coverage), a single comment summarizing all test points of your matrix
- [a status check](https://github.com/EnricoMi/publish-unit-test-result-action#commit-and-pull-request-checks) in the checks section of a commit and related pull requests reflects the test results
- [a single job summary](https://github.com/EnricoMi/publish-unit-test-result-action#github-actions-job-summary) is added to the GitHub Actions workflow run, not one for each test point in the matrix
- [a check summary](https://github.com/EnricoMi/publish-unit-test-result-action#github-actions-check-summary-of-a-commit) in the GitHub Actions section of the commit, plus test annotations similar to the `GitHubActionsTestLogger`
- works for fork pull requests and dependabot branches (not sure how `GitHubActionsTestLogger` performs here)

I hope this helps.

**Comment by EnricoMi** [comment]
GitHub Support states event file is save to upload:

> The event file will contain the full event payload data of the webhook that triggered the workflow run. It will not contain(now or in the future) any tokens or secrets. It is safe to use this payload.

**Comment by MoFtZ** [comment]
@EnricoMi Thanks for the extra information.

We don't really have clear requirements, but I'm currently wondering if this PR, and the current GitHubActionsTestLogger, is necessary.

Looking at the output in [this action](https://github.com/EnricoMi/ILGPU/actions/runs/4767698019), it appears to be very "noisy". A lot of artifacts and annotations are added to the build output, and I'm not sure anyone is actually doing anything with the information. Even the [current output](https://github.com/m4rs-mt/ILGPU/actions/runs/4803472845) is less than desirable.

@m4rs-mt Do you have any thoughts on this? I'm personally not reading any of the test summary outputs.

**Comment by EnricoMi** [comment]
> I'm personally not reading any of the test summary outputs.

This is actually a good argument for using the action rather than `GitHubActionsTestLogger`. The action adds comment to the pull request summarizing all those noisy test results. No need to navigate to those summaries.

Sure, without either of them the CI would still alert when tests fail, but it **won't alert** when tests are accidentally removed, skipped or not executed at all. The action shows you that and makes signing off those changes part of the pull request review.

**Comment by MoFtZ** [comment]
Do you have an example of showing newly added or removed tests? I tried [creating a PR ](https://github.com/MoFtZ/ILGPU/pull/82) that removed some tests, but [the output ](https://github.com/MoFtZ/ILGPU/pull/82#issuecomment-1525480769)did not identify any changes.

**Pull request closed without merging**
