### PR TITLE
Allow building `net471` target without Windows

### PR DESCRIPTION
**Pull request by lostmsu**

### CODE REVIEW

**Review by MoFtZ — CHANGES_REQUESTED** [review]
QUESTION: `Microsoft.NETFramework.ReferenceAssemblies` is an interesting Nuget package - first time I have heard of it. Should we be using the more specific `Microsoft.NETFramework.ReferenceAssemblies.net471`?

Also, if we plan on using this Nuget package, we should apply it to all the other locations in ILGPU too. e.g. unit test projects.

**Comment by lostmsu** [comment]
For the reference, [official doc](https://github.com/Microsoft/dotnet/tree/master/releases/reference-assemblies).

AFAIK Microsoft recommends using the "meta-package", however, I used specific version too without any issues.

Only the projects, that target .NET Framework need this. It just allows .NET SDK to build `net4xx` target on non-Windows OS and on Windows OS where SDK targeting pack is not installed. I noticed now, that test projects actually have `net471` too, but only for GitHub actions. I don't think this change is needed for GitHub actions, because unless you want to add Mono to your test matrix, there's no point in building `net471` test target on non-Windows.

**Review by MoFtZ — APPROVED** [review]

**Comment by lostmsu** [comment]
@MoFtZ  do you want me to rebase this?

**Comment by MoFtZ** [comment]
This is unlikely to cause conflicts, so no need to rebase. Just wait for @m4rs-mt to review.

**Review by m4rs-mt — APPROVED** [review]
Looks also good to me 👍 Thanks a lot for this simplification!

**Pull request merged**
