### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by c-rindi**
Add Code of Conduct to project - feedback welcome.

### CODE REVIEW

**Comment by MoFtZ** [comment]
hi @c-rindi, I'm not too familiar with Codes of Conduct as it applies to an open source project.

Under the `Attribution` section, there are several Codes of Conduct listed as reference. Also, in Github, under `Insights` -> `Community`, there are two further examples - the `Contributor Covenant` and `Citizen Code of Conduct`.

Do you know how these Codes of Conducts differ from each other, and how do they differ from the one you have proposed?

It is a case where some have "better" wording/phrasing for specific sections? Or are there omissions in some of the Codes of Conduct?

**Comment by Yey007** [comment]
Of course, for something like this we need to get everyone's opinions, which hopefully shouldn't be that hard as the project isn't huge.

**Comment by c-rindi** [comment]
Thanks for reading through it and giving feedback @MoFtZ @Yey007. 

The Code of Conduct is intended to continue fostering a cooperative, civil, and professional project (already evident here) and make sure that everyone feels welcome to contribute, by being intentional about it.

The two Github options (Contributor Convenant and Citizen Code of Conduct) that @MoFtZ mentions are great templates, and this CoC drew language from both of them. 

This proposed CoC is a bit more thorough: it calls out guiding values, includes some term definitions, and good behaviour examples. It has been reviewed by the G-Research legal team, as the same text is also in use for Codes of Conduct for other projects such as Fantomas, Armada, geras, and consuldotnet, among others.

Regarding @Yey007's question around infrastructure, for those other projects, any incoming communications to the Conduct email address is distributed (forwarded) to multiple maintainers and project contributors, so the same could be done with conduct@ilgpu.net.

Thank you again for the discussion. Let me know if there are any other questions.

**Comment by Yey007** [comment]
Alright, sounds good.

**Pull request merged**
