### PR TITLE
Added breaking unit test when using if statement with multiple clauses

### PR DESCRIPTION
**Pull request by MoFtZ**
hi @m4rs-mt, just ran into this code generation issue, and was able to create a simplified unit test.

Not really sure how to fix at the moment, but will dig around.

### CODE REVIEW

**Comment by MoFtZ** [comment]
Phew.. I'm exhausted.
On the plus side, I worked out the problem.

In IR\Analyses\CFG.cs:450, we add successors/predecessors to each of the blocks. However, because the code iterates over a dictionary, the order of adding successors is non-deterministic.

Later, in IR\Construction\IRRebuilder.cs:77, we copy the blocks in Scope, again in an unordered way.

Finally, in Backends\PTX\PTXCodeGenerator.cs:406, when generating the kernel code, we perform a mapping of Phi arguments from predecessor nodes. However, by this stage, the order of predecessors/successors has changed since the original Phi node was created.

The crash occurred because the Phi arguments had swapped (because the order of adding successors/predecessors was different).

As a fix, I have ordered the Blocks by ID.
Can you see any issues with this fix? or do you have a suggestion for a better solution?

**Comment by MoFtZ** [comment]
Damn, forgot to check the CUDA unit tests - they failed because something else must be unordered.

Will have to try again.

**Comment by MoFtZ** [comment]
OK, changed PhiNode to be immutable again. Hopefully I replaced the PhiValue correctly.

**Comment by m4rs-mt** [comment]
I guess it's not enough to revert the commit mentioned. However, it was intended to remove explicit tracking of predecessors to simplify upcoming transformations.

In the case of ILGPU, it may not be necessary to use different dialects for SPIR-V and CUDA.
A number of additional nodes (such as a `Loop` node) may be advantageous, as they allow high-level constructs to be expressed within the IR.

Block arguments will definitely simplify many transformations and make the integration of lambda functions much easier, I guess.

**Pull request merged**
