### PR TITLE
Enable codeql analysis

### PR DESCRIPTION
**Pull request by ljubon**
Example run: https://github.com/ljubon/ILGPU/actions/runs/1036318600
View alerts: https://imgur.com/a/245naZT
https://github.com/m4rs-mt/ILGPU/issues/539

### CODE REVIEW

**Comment by m4rs-mt** [comment]
@ljubon looks like the analysis phase instantly fails. Any idea what the problem might be?

**Comment by jgiannuzzi** [comment]
> looks like the analysis phase instantly fails. Any idea what the problem might be?

I believe the problem comes from the malformed `global.json` file. This should be fixed by #729.

**Comment by jgiannuzzi** [comment]
@ljubon now that #729 has been merged, rebasing on `master` should help with this PR.

**Comment by ljubon** [comment]
> @ljubon now that #729 has been merged, rebasing on `master` should help with this PR.



> @ljubon now that #729 has been merged, rebasing on `master` should help with this PR.

Hi @jgiannuzzi @m4rs-mt , sorry for my late reply
As it's just rebased, l hope it will resolve the issue, anyway I'll follow up later today and provide a fix/solution if the issue is still present.
Thank you both!

**Comment by m4rs-mt** [comment]
@ljubon @jgiannuzzi Thank you for your comments. Unfortunately it looks like the problem still exists....

**Comment by jgiannuzzi** [comment]
@ljubon @m4rt-mt adding a step to setup the latest .NET 6 SDK before the CodeQL jobs should do the trick

**Comment by ljubon** [comment]
> @ljubon @m4rs-mt adding a step to setup the latest .NET 6 SDK before the CodeQL jobs should do the trick

switching to `windows-latest` and adding setup job for .NET 6.0 worked 👌 
Thanks, @jgiannuzzi !

**Pull request merged**
