### PR TITLE
Added metapackage containing all ILGPU libraries.

### PR DESCRIPTION
**Pull request by MoFtZ**
Not sure if we want this meta-package or not, but might be useful.
Also not sure about the name.

### CODE REVIEW

**Comment by m4rs-mt** [comment]
@MoFtZ I really like this idea 👍 

I have to admit that I prefer @jgiannuzzi's idea of creating a "new" `ILGPU` package instead of an `ILGPU.All` package.

**Comment by MoFtZ** [comment]
@jgiannuzzi @m4rs-mt
I agree that the name `ILGPU.All` is not great. However, I was trying to avoid a breaking change. Also, it matched some existing names like `Microsoft.AspNetCore.All`.

I'll put this PR on hold until we decide on a timeframe (and name?).

**Comment by MoFtZ** [comment]
Something else to consider, if we rename `ILGPU` to `ILGPU.Core`, are we only renaming the nuget package? Or all the files/folders?

That would include:
- `Src/ILGPU` to `Src/ILGPU.Core`
- `Src/ILGPU.Tests` to `Src/ILGPU.Core.Tests`
- etc

**Comment by MoFtZ** [comment]
Renames the ILGPU nuget package to ILGPU.Core.
Adds a new ILGPU metapackage.

**Comment by MoFtZ** [comment]
Abandoning this PR.

In the future e.g. v2, it will be easier to deprecate `ILGPU.Algorithms` and release the `ILGPU` package with `ILGPU.Algorithms` baked in.

**Pull request closed without merging**
