### PR TITLE
Add ILGPU.Tests

### PR DESCRIPTION
**Pull request by mikhail-khalizev**
Add ILGPU.Tests project.

### CODE REVIEW

**Comment by m4rs-mt** [comment]
@mikhail-khalizev I will publish all internal tests in the next days in a separate repository called `ILGPU.Tests`. I suggest that we move your new tests to this repository and connect both via a git submodule. What do you think?

**Comment by m4rs-mt** [comment]
May be we can port your test cases to the existing test framework at [https://github.com/m4rs-mt/ILGPU.Tests](url)?

**Comment by mikhail-khalizev** [comment]
Hi. That's good. Only one question, why you want to use separate repository? Usually library and tests for it placed in same repository.

**Comment by mikhail-khalizev** [comment]
> May be we can port your test cases to the existing test framework at [https://github.com/m4rs-mt/ILGPU.Tests](url)?

Yes,  I will look.

**Comment by m4rs-mt** [comment]
Yes, you're absolutely right. The reason for this is that I have received many requests to create a separate repository for the test cases to make it easier (for them?) to distinguish between actual compiler commits and test updates. But maybe we want to change that in the future :)

**Comment by m4rs-mt** [comment]
I published all internal test cases (merged into the main repository).

**Comment by mikhail-khalizev** [comment]
Add #24.

**Pull request closed without merging**
