### PR TITLE
Applied general cleanup.

### PR DESCRIPTION
**Pull request by MoFtZ**
Ran `Code Cleanup` in VS2019 and fixed warnings when compiling with `net5.0`.

Updated indentation of ILGPU.csproj, since it is the only one using a different indentation. Also did some minor updates to the csproj files e.g. arranged the version number elements into their own Property Group.

Sealed all exception classes, and added standard Exception constructors.

### CODE REVIEW

**Comment by jgiannuzzi** [comment]
Just tried building this branch locally with .NET 5.0.301 and most warnings are gone! 🥳

However, I am still getting a bunch of warnings like this one for `ILGPU.Algorithms.Tests.*`:
```
m4rs-mt/ILGPU/Src/ILGPU.Algorithms.Tests.CPU/Configurations.cs(219,33): warning CA1707: Remove the underscores from type name ILGPU.Algorithms.Tests.CPU.CPUReductionExtensionTests_O2
```

**Comment by MoFtZ** [comment]
@jgiannuzzi I am not able to reproduce those warnings.. any ideas?

```
C:\dev\ILGPU> dotnet new globaljson --sdk-version 5.0.301
The template "global.json file" was created successfully.

C:\dev\ILGPU>dotnet build --configuration=Release -p:TreatWarningsAsErrors=true Src
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\dev\ILGPU\Src\ILGPU\ILGPU.csproj (in 238 ms).
  Restored C:\dev\ILGPU\Src\ILGPU.Algorithms\ILGPU.Algorithms.csproj (in 378 ms).
  Restored C:\dev\ILGPU\Src\ILGPU.Tests.Cuda\ILGPU.Tests.Cuda.csproj (in 1.09 sec).
  Restored C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests.OpenCL\ILGPU.Algorithms.Tests.OpenCL.csproj (in 1.08 sec).
  Restored C:\dev\ILGPU\Src\ILGPU.Tests.CPU\ILGPU.Tests.CPU.csproj (in 1.17 sec).
  Restored C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests.CPU\ILGPU.Algorithms.Tests.CPU.csproj (in 1.18 sec).
  Restored C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests.Cuda\ILGPU.Algorithms.Tests.Cuda.csproj (in 1.18 sec).
  Restored C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests\ILGPU.Algorithms.Tests.csproj (in 1.19 sec).
  Restored C:\dev\ILGPU\Src\ILGPU.Tests\ILGPU.Tests.csproj (in 808 ms).
  Restored C:\dev\ILGPU\Src\ILGPU.Tests.OpenCL\ILGPU.Tests.OpenCL.csproj (in 835 ms).
  1 of 11 projects are up-to-date for restore.
  ILGPU -> C:\dev\ILGPU\Bin\Release\net5.0\ILGPU.dll
  ILGPU -> C:\dev\ILGPU\Bin\Release\netstandard2.1\ILGPU.dll
  ILGPU -> C:\dev\ILGPU\Bin\Release\net47\ILGPU.dll
  ILGPU.Algorithms -> C:\dev\ILGPU\Bin\Release\netstandard2.1\ILGPU.Algorithms.dll
  ILGPU.Algorithms -> C:\dev\ILGPU\Bin\Release\net5.0\ILGPU.Algorithms.dll
  ILGPU.Tests -> C:\dev\ILGPU\Src\ILGPU.Tests\bin\Release\netcoreapp3.1\ILGPU.Tests.dll
  ILGPU.Tests -> C:\dev\ILGPU\Src\ILGPU.Tests\bin\Release\net5.0\ILGPU.Tests.dll
  ILGPU.Tests.OpenCL -> C:\dev\ILGPU\Src\ILGPU.Tests.OpenCL\bin\Release\netcoreapp3.1\ILGPU.Tests.OpenCL.dll
  ILGPU.Tests.CPU -> C:\dev\ILGPU\Src\ILGPU.Tests.CPU\bin\Release\netcoreapp3.1\ILGPU.Tests.CPU.dll
  ILGPU.Tests.Cuda -> C:\dev\ILGPU\Src\ILGPU.Tests.Cuda\bin\Release\netcoreapp3.1\ILGPU.Tests.Cuda.dll
  ILGPU.Algorithms.Tests -> C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests\bin\Release\netcoreapp3.1\ILGPU.Algorithms.Tests.dll
  ILGPU.Algorithms -> C:\dev\ILGPU\Bin\Release\net47\ILGPU.Algorithms.dll
  ILGPU.Algorithms.Tests.Cuda -> C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests.Cuda\bin\Release\netcoreapp3.1\ILGPU.Algorithms.Tests.Cuda.dll
  ILGPU.Tests.CPU -> C:\dev\ILGPU\Src\ILGPU.Tests.CPU\bin\Release\net5.0\ILGPU.Tests.CPU.dll
  ILGPU.Tests.OpenCL -> C:\dev\ILGPU\Src\ILGPU.Tests.OpenCL\bin\Release\net5.0\ILGPU.Tests.OpenCL.dll
  ILGPU.Tests.Cuda -> C:\dev\ILGPU\Src\ILGPU.Tests.Cuda\bin\Release\net5.0\ILGPU.Tests.Cuda.dll
  ILGPU.Algorithms.Tests.CPU -> C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests.CPU\bin\Release\netcoreapp3.1\ILGPU.Algorithms.Tests.CPU.dll
  ILGPU.Algorithms.Tests.OpenCL -> C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests.OpenCL\bin\Release\netcoreapp3.1\ILGPU.Algorithms.Tests.OpenCL.dll
  ILGPU.Algorithms.Tests -> C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests\bin\Release\net5.0\ILGPU.Algorithms.Tests.dll
  ILGPU.Algorithms.Tests.OpenCL -> C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests.OpenCL\bin\Release\net5.0\ILGPU.Algorithms.Tests.OpenCL.dll
  ILGPU.Algorithms.Tests.CPU -> C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests.CPU\bin\Release\net5.0\ILGPU.Algorithms.Tests.CPU.dll
  ILGPU.Algorithms.Tests.Cuda -> C:\dev\ILGPU\Src\ILGPU.Algorithms.Tests.Cuda\bin\Release\net5.0\ILGPU.Algorithms.Tests.Cuda.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

**Comment by jgiannuzzi** [comment]
@MoFtZ I can only reproduce it on a clean build - I think it's because `Configurations.cs` are generated files

**Comment by MoFtZ** [comment]
Got it - for some reason, after clean build, building the solution with `net5.0` produces warnings in `Configurations.cs` on the ILGPU.Algorithms.Tests.* projects, but for whatever reason, not the ILGPU.Tests.* projects. Updated the PR to ignore these warnings.

**Review by m4rs-mt — APPROVED** [review]

**Pull request merged**
