### PR TITLE
Updated nuget package dependencies in .nuspec file.

### PR DESCRIPTION
**Pull request by MoFtZ**

### CODE REVIEW

**Comment by m4rs-mt** [comment]
I had the same idea several minutes ago 😄

**Comment by m4rs-mt** [comment]
I am going to update the version number and the .nuspec file structure a bit after merging

**Comment by MoFtZ** [comment]
With the simplified Release-only nuget package, it might be possible to drop the `.nuspec` file and move the fuctionality into the `.csproj` file. That would simplify having to maintain the list of dependencies in multiple files.

**Comment by m4rs-mt** [comment]
We can even think about removing the `.targets` file, since Nuget should be able to wire the framework assemblies automatically - in theory.

**Comment by m4rs-mt** [comment]
You can also do this in the current PR if you like 🤓

**Pull request merged**
